addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings" % "1.1.4")
addSbtPlugin("com.eed3si9n"        % "sbt-assembly"         % "2.3.1")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.4.4")
addSbtPlugin("net.virtual-void"    % "sbt-dependency-graph" % "0.9.2")
addSbtPlugin("com.github.sbt"      % "sbt-native-packager"  % "1.11.7")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.6.0")
