MERGE INTO test.table_a t_s
USING (SELECT * FROM test.staged_a) t_o
ON t_s.ARCANE_MERGE_KEY = t_o.ARCANE_MERGE_KEY
WHEN MATCHED AND t_s.SYS_CHANGE_OPERATION = 'D' THEN DELETE
WHEN MATCHED AND t_s.SYS_CHANGE_OPERATION != 'D' AND t_s.SYS_CHANGE_VERSION > t_o.SYS_CHANGE_VERSION THEN SET
   colA = t_s.colA,
   colB = t_s.colB
WHEN NOT MATCHED AND t_s.SYS_CHANGE_OPERATION != 'D' THEN INSERT (ARCANE_MERGE_KEY, colA, colB)
VALUES (
  t_s.colA,
  t_s.colB
)
