{{- if .Values.rbac.clusterRole.jobEditor.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "app.clusterRole.jobEditor" . }}
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    {{- include "app.labels" $ | nindent 4 }}
    {{- with .Values.rbac.clusterRole.jobEditor.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.rbac.clusterRole.jobEditor.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - verbs:
      - patch
    apiGroups:
      - batch
    resources:
      - jobs
{{- end }}
