{{- if and .Values.rbac.clusterRole.jobEditor.create .Values.rbac.clusterRoleBindings.create -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "app.clusterRole.jobEditor" . }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
    {{- with .Values.rbac.clusterRoleBindings.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.rbac.clusterRoleBindings.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ template "app.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "app.clusterRole.jobEditor" . }}
  
{{- end }}
