apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sql-server-ct-streams.streaming.sneaksanddata.com
spec:
  group: streaming.sneaksanddata.com
  scope: Namespaced
  names:
    plural: sql-server-ct-streams
    singular: sql-server-ct-stream
    kind: SqlServerChangeTracking
    shortNames:
      - sqlcts
  versions:
    - name: v1beta1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Table
          type: string
          jsonPath: .spec.table
        - name: Schema
          type: string
          jsonPath: .spec.schema
        - name: Refresh Interval
          type: string
          jsonPath: .spec.changeCaptureIntervalSeconds
        - name: Sink location
          type: string
          jsonPath: .spec.sinkLocation
        - name: Phase
          type: string
          jsonPath: .status.phase
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                connectionStringRef:
                  description: |
                    Name of the secret containing the connection string.
                    The secret should have a key named 'ARCANE_CONNECTIONSTRING'.
                  type: object
                  properties:
                    name:
                      type: string
                catalogAuthSecretRef:
                  description: |
                    Name of the secret containing the catalog authentication.
                    The secret should have the following mandatory keys:
                      - ARCANE_FRAMEWORK__S3_CATALOG_AUTH_CLIENT_URI
                      - ARCANE_FRAMEWORK__S3_CATALOG_AUTH_SCOPE
                    And the authentication information in the following keys:
                      - ARCANE_FRAMEWORK__S3_CATALOG_AUTH_CLIENT_ID
                      - ARCANE_FRAMEWORK__S3_CATALOG_AUTH_CLIENT_SECRET
                    OR
                      - ARCANE_FRAMEWORK__S3_CATALOG_AUTH_INIT_TOKEN

                    The authentication information is mutually exclusive.
                    If init token is provided, client id and secret are not used.
                  type: object
                  properties:
                    name:
                      type: string
                catalog:
                  type: object
                  properties:
                    namespace:
                      type: string
                    warehouse:
                      type: string
                    uri:
                      type: string
                    authSecretRef:
                      description: |
                        Not used in the operator version 0.0.x
                        In operator version 0.1.x and above this field will replace the `catalogAuthSecretRef` field.
                      type: object
                      properties:
                        name:
                          type: string
                optional: true
                default: null # for backward compatibility
                mergeService:
                  type: object
                  properties:
                    uri:
                      type: string
                    authSecretRef:
                      description: |
                        Not used in the operator version 0.0.x
                        In operator version 0.1.x and above this field will replace the `mergeAuthSecretRef` field.
                      type: object
                      properties:
                        name:
                          type: string
                  optional: true
                  default: null # for backward compatibility
                mergeAuthSecretRef:
                  #TODO: Add the keys required in the secret.
                  description: |
                    Name of the secret containing the data storage authentication for the merge service.
                    The secret should have a key named 'ARCANE_FRAMEWORK__MERGE_SERVICE__JDBC_URL'.
                  type: object
                  properties:
                    name:
                      type: string
                  optional: true
                  default: null # for backward compatibility
                stagingStorageAuthSecretRef:
                  description: |
                    Name of the secret containing the data storage authentication for the S3 bucket containing staging data.
                    The secret should have the following mandatory keys:
                      - ARCANE_FRAMEWORK__S3_CATALOG_SECRET_ACCESS_KEY
                      - ARCANE_FRAMEWORK__S3_CATALOG_ACCESS_KEY_ID
                      - ARCANE_FRAMEWORK__S3_CATALOG_ENDPOINT
                      - ARCANE_FRAMEWORK__S3_CATALOG_REGION
                      - AWS_REGION
                    The AWS_REGION key is used to set the region for the AWS SDK and it's value should be
                    the same as ARCANE_FRAMEWORK__S3_STAGING_CATALOG_REGION.
                  type: object
                  properties:
                    name:
                      type: string
                  optional: true
                  default: null # for backward compatibility
                stagingStorage:
                  authSecretRef:
                    description: |
                      Not used in the operator version 0.0.x
                      In operator version 0.1.x and above this field will replace the `stagingStorageAuthSecretRef` field.
                    type: object
                    properties:
                      name:
                        type: string
                  optional: true
                  default: null # for backward compatibility
                jobTemplateRef:
                  description: |
                    Name of the job template to be used for the streaming job if stream is running in normal mode.
                  type: object
                  properties:
                    name:
                      type: string
                    kind:
                      type: string
                    apiGroup:
                      type: string
                  default:
                    apiGroup: streaming.sneaksanddata.com
                    kind: StreamingJobTemplate
                    name: standard-job
                backfillJobTemplateRef:
                  description: |
                    Name of the job template to be used for the streaming job if stream is running in backfill mode.
                  type: object
                  properties:
                    name:
                      type: string
                    kind:
                      type: string
                    apiGroup:
                      type: string
                  default:
                    apiGroup: streaming.sneaksanddata.com
                    kind: StreamingJobTemplate
                    name: large-job
                schema:
                  type: string
                  description: The schema to track changes for.
                table:
                  type: string
                  description: The table to track changes for.
                rowsPerGroup:
                  type: integer
                  description: Number of rows per parquet row group.
                groupingIntervalSeconds:
                  type: integer
                  description: Max time to wait for rowsPerGroup to accumulate. Can be from 1 to 60 seconds.
                  minimum: 1
                  maximum: 60
                groupsPerFile:
                  type: integer
                  description: Number of row groups per file.
                sinkLocation:
                  type: string
                  description: Data location for parquet files.
                commandTimeout:
                  type: integer
                  description: Number of seconds to wait for result before sql commands should time out.
                lookBackInterval:
                  type: integer
                  description: Number of seconds to look back when determining first set of changes to extract.
                changeCaptureIntervalSeconds:
                  type: integer
                  description: How long to wait before polling for next result set. Can be from 1 to 60 seconds.
                  minimum: 1
                  maximum: 60
                streamMetadata:
                  type: object
                  optional: true
                  default: null
                  properties:
                    datePartition:
                      type: object
                      properties:
                        description:
                          type: string
                        fieldName:
                          type: string
                        fieldFormat:
                          type: string
                        fieldExpression:
                          type: string
                    partitions:
                      type: array
                      items:
                        type: object
                        properties:
                          description:
                            type: string
                          fieldName:
                            type: string
                          fieldFormat:
                            type: string
                stagingLocation:
                  type: string
                  description: Data location for staging files.
                  optional: true
                  default: null # for backward compatibility
                retention:
                  type: object
                  properties:
                    retentionPeriod:
                      type: integer
                      description: Number of days to retain data.
                    retentionUnit:
                      optional: true
                      default: hours
                      type: string
                      enum:
                        - days
                        - hours
                        - minutes
                    location:
                      type: string
                      description: Data location for retention table.
                  optional: true
                  default: null # for backward compatibility
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - RESTARTING
                    - RUNNING
                    - RELOADING
                    - TERMINATING
                    - STOPPED
                    - SUSPENDED
                    - FAILED
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - status
                      - type
                    properties:
                      message:
                        type: string
                      phase:
                        type: string
                      type:
                        type: string
                        enum:
                          - WARNING
                          - ERROR
                          - INFO
                          - READY
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
