apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sql-server-ct-streams.streaming.sneaksanddata.com
spec:
  group: streaming.sneaksanddata.com
  scope: Namespaced
  names:
    plural: sql-server-ct-streams
    singular: sql-server-ct-stream
    kind: SqlServerChangeTracking
    shortNames:
      - sqlcts
  versions:
    - name: v1beta1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Table
          type: string
          jsonPath: .spec.table
        - name: Schema
          type: string
          jsonPath: .spec.schema
        - name: Refresh Interval
          type: string
          jsonPath: .spec.changeCaptureIntervalSeconds
        - name: Sink location
          type: string
          jsonPath: .spec.sinkLocation
        - name: Phase
          type: string
          jsonPath: .status.phase
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                connectionStringRef:
                  description: |
                    Name of the secret containing the connection string.
                    Should have a key named 'ARCANE_CONNECTIONSTRING'.
                  type: object
                  properties:
                    name:
                      type: string
                jobTemplateRef:
                  description: |
                    Name of the job template to be used for the streaming job if stream is running in normal mode.
                  type: object
                  properties:
                    name:
                      type: string
                    kind:
                      type: string
                    apiGroup:
                      type: string
                  default:
                    apiGroup: streaming.sneaksanddata.com
                    kind: StreamingJobTemplate
                    name: standard-job
                backfillJobTemplateRef:
                  description: |
                    Name of the job template to be used for the streaming job if stream is running in backfill mode.
                  type: object
                  properties:
                    name:
                      type: string
                    kind:
                      type: string
                    apiGroup:
                      type: string
                  default:
                    apiGroup: streaming.sneaksanddata.com
                    kind: StreamingJobTemplate
                    name: large-job
                schema:
                  type: string
                  description: The schema to track changes for.
                table:
                  type: string
                  description: The table to track changes for.
                rowsPerGroup:
                  type: integer
                  description: Number of rows per parquet row group.
                groupingIntervalSeconds:
                  type: integer
                  description: Max time to wait for rowsPerGroup to accumulate. Can be from 1 to 60 seconds.
                  minimum: 1
                  maximum: 60
                groupsPerFile:
                  type: integer
                  description: Number of row groups per file.
                sinkLocation:
                  type: string
                  description: Data location for parquet files.
                commandTimeout:
                  type: integer
                  description: Number of seconds to wait for result before sql commands should time out.
                lookBackInterval:
                  type: integer
                  description: Number of seconds to look back when determining first set of changes to extract.
                changeCaptureIntervalSeconds:
                  type: integer
                  description: How long to wait before polling for next result set. Can be from 1 to 60 seconds.
                  minimum: 1
                  maximum: 60
                streamMetadata:
                  type: object
                  optional: true
                  default: null
                  properties:
                    partitions:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          fieldName:
                            type: string
                          fieldFormat:
                            type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - RESTARTING
                    - RUNNING
                    - RELOADING
                    - TERMINATING
                    - STOPPED
                    - SUSPENDED
                    - FAILED
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - status
                      - type
                    properties:
                      message:
                        type: string
                      phase:
                        type: string
                      type:
                        type: string
                        enum:
                          - WARNING
                          - ERROR
                          - INFO
                          - READY
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
