{{- if .Values.customResourceDefinitions.create }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name:  microsoft-sql-server-streams.streaming.sneaksanddata.com
spec:
  group: streaming.sneaksanddata.com
  scope: Namespaced
  names:
    plural: microsoft-sql-server-streams
    singular: microsoft-sql-server-stream
    kind: MicrosoftSqlServerStream
    shortNames:
      - mssql-stream
  versions:
    - name: v1beta1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Table
          type: string
          jsonPath: .spec.sourceSettings.table
        - name: Schema
          type: string
          jsonPath: .spec.sourceSettings.schema
        - name: Refresh Interval
          type: string
          jsonPath: .spec.sourceSettings.changeCaptureIntervalSeconds
        - name: Target table name
          type: string
          jsonPath: .spec.sinkSettings.targetTableName
        - name: Phase
          type: string
          jsonPath: .status.phase
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tableProperties:
                  type: object
                  default:
                    partitionExpressions: []
                    sortedBy: []
                    parquetBloomFilterColumns: []
                    format: PARQUET
                  properties:
                    partitionExpressions:
                      type: array
                      items:
                        type: string
                      default: []
                    sortedBy:
                      type: array
                      items:
                        type: string
                      default: [ ]
                    parquetBloomFilterColumns:
                      type: array
                      items:
                        type: string
                      default: [ ]
                    format:
                      type: string
                      enum:
                        - PARQUET
                        - ORC
                        - AVRO
                      default: PARQUET
                sourceSettings:
                  type: object
                  properties:
                    schema:
                      type: string
                      description: The schema to track changes for.
                    table:
                      type: string
                      description: The table to track changes for.
                    changeCaptureIntervalSeconds:
                      type: integer
                      description: How long to wait before polling for next result set. Can be from 1 to 1 hour.
                      minimum: 1
                      maximum: 3600
                    fetchSize:
                      type: integer
                      description: Gives the JDBC driver a hint as to the number of rows that should be fetched from the database when more rows are needed
                      default: 1024
                connectionStringRef:
                  description: |
                    Name of the secret containing the connection string.
                    The secret should have a key named 'ARCANE_CONNECTIONSTRING'.
                  type: object
                  properties:
                    name:
                      type: string
                jobTemplateRef:
                  description: |
                    Name of the job template to be used for the streaming job if stream is running in normal mode.
                  type: object
                  properties:
                    name:
                      type: string
                    kind:
                      type: string
                    apiGroup:
                      type: string
                  default:
                    apiGroup: streaming.sneaksanddata.com
                    kind: StreamingJobTemplate
                    name: standard-job
                backfillJobTemplateRef:
                  description: |
                    Name of the job template to be used for the streaming job if stream is running in backfill mode.
                  type: object
                  properties:
                    name:
                      type: string
                    kind:
                      type: string
                    apiGroup:
                      type: string
                  default:
                    apiGroup: streaming.sneaksanddata.com
                    kind: StreamingJobTemplate
                    name: large-job
                rowsPerGroup:
                  type: integer
                  description: Number of rows per parquet rowgroup.
                groupingIntervalSeconds:
                  type: integer
                  description: Max time to wait for rowsPerGroup to accumulate. Can be from 1 to 60 seconds.
                  minimum: 1
                  maximum: 3600
                sinkSettings:
                  type: object
                  properties:
                    optimizeSettings:
                      type: object
                      description: Data location for parquet files.
                      properties:
                        batchThreshold:
                          type: integer
                          default: 60
                          description: Number of batches to accumulate before running the optimization query.
                        fileSizeThreshold:
                          type: string
                          default: 100MB
                          description: File size to accumulate in the optimization query.
                      default:
                        batchThreshold: 60
                        fileSizeThreshold: 100MB
                    snapshotExpirationSettings:
                      type: object
                      description: Data location for parquet files.
                      properties:
                        batchThreshold:
                          type: integer
                          default: 60
                          description: Number of batches to accumulate before running the optimization query.
                        retentionThreshold:
                          type: string
                          default: 6h
                          description: File retention period.
                      default:
                        batchThreshold: 60
                        retentionThreshold: 6h
                    orphanFilesExpirationSettings:
                      type: object
                      description: Data location for parquet files.
                      properties:
                        batchThreshold:
                          type: integer
                          default: 60
                          description: Number of batches to accumulate before running the optimization query.
                        retentionThreshold:
                          type: string
                          default: 6h
                          description: File retention period.
                      default:
                        batchThreshold: 60
                        retentionThreshold: 6h
                    targetTableName:
                      type: string
                      description: Data location for parquet files.
                lookBackInterval:
                  type: integer
                  description: |
                    Number of seconds to look back when determining first set of changes to extract.
                    Can be set in interval from 1 second to 10 hours. Default is 1 hour.
                  minimum: 1
                  maximum: 1209600
                  default: 3600
                stagingDataSettings:
                  type: object
                  properties:
                    dataLocation:
                      type: string
                    maxRowsPerFile:
                      type: integer
                      description: The maximum number of rows per file in the staging table.
                      default: 10000
                    tableNamePrefix:
                      type: string
                    catalog:
                      type: object
                      properties:
                        catalogName:
                          type: string
                        schemaName:
                          type: string
                        namespace:
                          type: string
                        warehouse:
                          type: string
                        catalogUri:
                          type: string
                fieldSelectionRule:
                  type: object
                  properties:
                    ruleType:
                      type: string
                      enum:
                        - include
                        - exclude
                        - all
                    fields:
                      type: array
                      items:
                        type: string
                  default:
                    ruleType: all
                    fields: [ ]
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - RESTARTING
                    - RUNNING
                    - RELOADING
                    - TERMINATING
                    - STOPPED
                    - SUSPENDED
                    - FAILED
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - status
                      - type
                    properties:
                      message:
                        type: string
                      phase:
                        type: string
                      type:
                        type: string
                        enum:
                          - WARNING
                          - ERROR
                          - INFO
                          - READY
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
{{- end }}
