apiVersion: streaming.sneaksanddata.com/v1beta1
kind: StreamClass
metadata:
  name: {{ template "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "streamclass.labels" $ | nindent 4 }}
  {{- if .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  apiGroupRef: streaming.sneaksanddata.com
  kindRef: MicrosoftSqlServerStream
  apiVersion: v1beta1
  pluralName: microsoft-sql-server-stream
  secretRefs:
    - connectionStringRef
