name: Run tests with coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main]

jobs:
  validate_commit:
    name: Validate commit
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    permissions:
      id-token: write      # required for dependabot PRs
      pull-requests: write # required for dependabot PRs
      contents: read       # required for dependabot PRs

      checks: write       # required for cobertura-action
    steps:
      - uses: actions/checkout@v4
      - name: Setup Scala
        uses: japgolly/setup-everything-scala@v3.1
        with:
          java-version: temurin:1.23.0.1
      - name: Build the Docker Compose stack
        run: docker compose up --quiet-pull -d
      - name: Get Compose Logs
        if: always()
        run: docker compose logs

      - name: Import the environment variables
        run: cat integration-tests.env >> $GITHUB_ENV

      - name: Build and test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: sbt clean coverage test coverageReport

      - uses: 5monkeys/cobertura-action@v14
        with:
          path: ./target/scala-3.6.1/coverage-report/cobertura.xml
          minimum_coverage: 0
