name: Build Latest Apache Polaris Image for Tests

on: workflow_dispatch

jobs:
  build_image:
    name: Build Container Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: 'apache/polaris'
          ref: 'main'

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/apache-polaris

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
        with:
          use: true
          platforms: linux/amd64

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
