name: Remove old artifacts
on:
  # schedule:
  #   - cron: '0 12 * * *' # every day at 12:00 UTC
  workflow_dispatch:
    
jobs:
  remove_old_artifacts:
    name: Remove old artifacts
    runs-on: ubuntu-latest
    
    permissions: 
      contents: read
      packages: write
      
    timeout-minutes: 10 # stop the task if it takes longer

    steps:
      - name: Delete old package versions of ${{ github.event.repository.name  }}
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: ${{ github.event.repository.name  }}
          package-type: container
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 10
          delete-only-pre-release-versions: "true"
          
      - name: Delete old package versions of helm/${{ github.event.repository.name  }}
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: helm/${{ github.event.repository.name  }}
          package-type: container
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 10
          delete-only-pre-release-versions: "true"
